FROM {{ namespace }}/{{ image_prefix }}nexus:{{ tag }}

{% block labels %}
    LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block nexus_dns_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

# 只安装 DNS 特有的包
{% if base_package_type == 'rpm' %}
    {% set nexus_dns_packages = [
        'dnsmasq'
    ] %}
{% elif base_package_type == 'deb' %}
    {% set nexus_dns_packages = [
        'dnsmasq'
    ] %}
{% endif %}

{{ macros.install_packages(nexus_dns_packages | customizable("packages")) }}

{% block nexus_dns_setup %}
    # Create DNS-specific directories
    RUN mkdir -p /var/log/nexus/dnsmasq /etc/nexus/dns \
    && chown -R nexus:nexus /var/log/nexus/dnsmasq /etc/nexus/dns
{% endblock %}

{% block nexus_dns_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER nexus