name: Build Ceilometer Images

on:
  workflow_dispatch:  # 手动触发

env:
  REGISTRY: ghcr.io
  OWNER: ${{ github.repository_owner }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        service: [
          "ceilometer"
        ]
        base_distro: [
          "ubuntu"
        ]
        openstack_release: [
          "2024.2",
          "2025.1"
        ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip python3-dev build-essential libffi-dev

      - name: Install Kolla and Docker
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install kolla
          python3 -m pip install docker

      - name: Create kolla-build.conf
        run: |
          sudo mkdir -p /etc/kolla
          
          cat << EOF | sudo tee /etc/kolla/kolla-build.conf
          [DEFAULT]
          namespace = ${{ env.OWNER }}
          push = true
          tag = ${{ matrix.openstack_release }}
          base = ${{ matrix.base_distro }}
          registry = ${{ env.REGISTRY }}
          debug = true
          
          # 配置源代码仓库地址
          [ceilometer-base]
          type = git
          location = https://opendev.org/openstack/ceilometer
          reference = stable/${{ matrix.openstack_release }}
          EOF
          
          cat /etc/kolla/kolla-build.conf

      - name: Build and push image
        run: |
          echo "Building image for ${{ matrix.service }}"
          sudo -E python3 -m kolla.cmd.build ${{ matrix.service }}